---

# .travis.yml
#
# https://molecule.readthedocs.io/en/latest/usage.html#travis-ci

sudo: required

language: python

env:
  matrix:
    - IMAGE_NAME=ubuntu IMAGE_VERSION=16.04 ANSIBLE_GROUP=pg91
    - IMAGE_NAME=ubuntu IMAGE_VERSION=16.04 ANSIBLE_GROUP=pg92

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

install:
  - pip install testinfra
  - pip install docker-py
  - pip install molecule
  - pip install ansible-lint

before_script:
  - sed -e "s/IMAGE_NAME/${IMAGE_NAME}/g" \
        -e "s/IMAGE_VERSION/${IMAGE_VERSION/g" \
        -e "s/ANSIBLE_GROUP/${ANSIBLE_GROUP}/g" \
           molecule.yml.in > molecule.yml

script:
  # TODO: split into before_script, after_script, etc???
  - molecule syntax
  - molecule create
  - molecule status
  - molecule converge
  - molecule idempotence
  - molecule verify
