#
# Dockerfile for CentOS 7 removing requiretty from /etc/sudoers
#
# - https://github.com/docker/machine/issues/698
# - http://unix.stackexchange.com/questions/122616/why-do-i-need-a-tty-to-run-sudo-if-i-can-sudo-without-a-password

FROM centos:7
MAINTAINER "Markus Juenemann <markus@juenemann.net>"

RUN sed -i -e 's/^Defaults\s*requiretty/#Defaults   requiretty/g' /etc/sudoers